apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-apps
spec:
  interval: 30m0s
  path: ./base/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: uberwald
  validation: client
