apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-apps
spec:
  interval: 5m0s
  path: ./apps/monitoring/manifests
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: uberwald
  validation: client
