apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBN706C1sUWyU9tRaOc1+v66weE0hDai24l2zC5NbBKRuATSLXh17h7Dp2wMoPeTtyPI0fy+Bzc3d6N+fPoXIrUhxlvI28An7HS7JF6FFoltd/3EQfLwJDNs2SoRwNUBkX7Zfhg6FS6/qwuOjpzFBxzHvwsJUO/HoMPQpBxO6LDX6n9Nqy4BvwFpugSmUIr2T00kTePr7uuBpcNRxNCGpTYtoplxVUrnehmLYDr1kvhVzL8YTNhqewdI8QHSjaHl1tgLzKGzFbgBQuef3pqhP4l69Xtc6HSTB6+G1PUxraX6QO2pcLf7HjEeJ93zCncbleXWzvw1797jfD3p/7t0P1V63M6KILbcuGebH6eCNeDdSCBvrGbU3TKekrO7JUB+S4HjW8yrj91a2QDLCMT7BPYE3rH581WlAYIaxPmoEvYWHqvsnLmgV/TnJPwZesNOKwhmRhOGh3e8C8YNz6PvLpjLk+eejeL5dBljKnU+L8n8j7vyX30aeK8v2xgep38/HlPDS7sw6eh1ib0BmxBEMCrbW/XdcWp5XjLkbpB5mo/0BzTK2agF7lr/NzNa8WM4cbw/6UuMThq9zC53RF6umUYVF0EECfxf+gz1qobopoCWbqj76eh+KL3xytfHQUtdH7YoS4tHhQTR+RPsWxkofLHcbmOySdEbG7AOPAiZ0jlBxOAL+AcA1ziHjEr9PPZP1XMO39CPoWni7oIbcQRQ980b4iHd0APv5NZLxybSCUy3BANatOOs4sO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-webhook-token
      namespace: flux-system
