apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBGYhtSEMdIfAf7bV+AYWDJRd6JLQL5iBTFPr1dO0Y5kwfIOjsseLTckvl4ScpLJ6tZmbYDSyIoftxxYye9ARHv6UIFG7ESzkFa0eC9CqE88LdSVjCODZxp6erqIfoVSXutLRsnPyfPNjlAGkPY5M9TR1wmNDAH+F1u8y3DMbjaeH2OUH+WbLkDp6YOyoPE2ES6JAqIqy6W9G45Xr2UES6mCxkPxZ5jx3cRC54tcO3qvXa2TV9uHkchUpCNyDK0Fm2Hba9wZErsxZfklUgjuyxen5na49BXU7X6VmCqiwVGxw3xv8bi/98JTRHJa/80IEolNJRIGqGx6bi1Cnx0w6xbNI1Aa5Yc4zp1CWVGa6hvX+zDf6L/kx7deDe4uyJL7EzZnnAj6Qaysc27lAj3iS0rUOOzBoGyDjoEL5THEjXJoDrwoSIO6rrmLdxeIUhgou9+tQybfDSjZeKTf/7nVP6VO8a7HzzRDi0RlcFrf3b/mb16rH9CANnmMGrsmwNP9GFa5u9Pa2yqhRzbz6Zr7TWfwc+JTYCXymFc0oCxJ1eZMR191/fLsW9svVOaB4kbVsOcq8dNy+G8Jag2SGRUB8PyS6wBxaZk4cgFINpzbbcB1hf+iovl1v9OhyF0/8DWQIJChgESsI2aCIdGj0XTUmvra1dcwcnQBj+8EAmuPTlThC8f+I9EtUpsmuoOo0hvv5y8DQZdWsi0Sr1RsO46nl4kNePBZ1MkkLdhJSpxbYP/ZGe86jU0Au2/y2+IXmROtP7FP9gWjEc8ixn17eEl9MPAd5AYmT8uerokHEPCSIeQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
