---
miniflux:
  namespace: news
  version: "2.0.33"  # application-version-from-github: miniflux/v2
  image: "miniflux/miniflux:2.0.33"  # application-image-from-github: miniflux/v2
  domain: "news.krupa.net.pl"
  resources:
    requests:
      cpu: 3m
      memory: 30Mi
    limits:
      cpu: 50m
      memory: 100Mi
  admin:
    user: "AgCwdCVdKVM9832LU7H8fzMCzsvn1jLXfiMhcGy7m7QKchCoRIqhUakKcVVvVaWy15fYp3bMhSnh5uR/cmFCkjJ9qI/sSBgKsm7lUf6bDN5oy+vJ2TztjE6PVGvuBIsI/gk9YcCmVh1xMMmY2ZaGsyMvbOLLOudF9xUE0x6XWvg/qqTN/E+IRQLItkSSle1xsCR+C1WtYSFP7PyowdgmUMLdvYkjTU2rEmyCDIyChSrAnIPs0xbyri/b0mHYtdv8RfKUwYEmKggB98ZEMTEpY1RsWkYYnUweT+TpJa9iVd5jzKQQWXNkoyREdfAUEWZUF2tmqSh3Vct8Abc/Cth92RKYC7Q2o5rFfEQ2aLiN45YfxEqJrhy0L+Yso85LCUH246JlEFy7j5JxMMtYQTjkzdO5pQmtJvgHKS/Z8rykBsSyBp4oxBfjx6VWHBXdPbbVBnUGwPOzcJAHncdbTjXH/Kiatvl5084a+Uu8Sguatm096k42v23xyzVOSj90AoHRmU0w+yUEjIK+s7oHHwmiqGsmvAylBGimM0AzY1tScpr5hkS1BaXNGzBU8mChf3WVRCE6uvWr69wxHRyPRs6vDwjoJtBm2RMZbg0OF1x1KdRplE94mKpj4V7kkqRhNDZFyx2MY6sP1DT77nzry7tVNH+YG3Jj+eFNWasORyp8O8/moOO+6XOs64tHesySgkCyhJuNqB0VAQ=="
    pass: "AgBraZxeFnZS9whfA3Wdx95QN6uGOlUeeVecNPFQNq74pF8rEcctZNLA4SyF5jexz+3JvuG38b900h5yMM7xfVOHJEf1PZLvBB6H7RaMJXbFMj8gFW6WVBRUrOh8T6Cm/3+PqNreRUVJChO6Jltc1D/62MBAhlZ9SuMrQOd0GN4sqTNR9bZhNvK1unISmWsl2/jODsKAGNj57oXYpxBS66v0xg5UXhueus50dv0YqKto/rQo+PFBQloPxV1pN199ypgg559VG0+xMK0Q4OJFWQtx3dTHXiAYxZkQHB/MI/Go+8/Zq9cQCvMKxcLqoiWd6R1hWqNvW6c7+m/KG7c0fVnOKL2KwZ61VWTXgh0rfLyKc55/adn9aLUHargrGdWNwvl5fmAm8E4IZXADJisVFnxiXpaeY9tL3nDdeiUgCFcbOfFFzdFnFENppoP7uIdhE63bn2qq50HQh2Zf+6D88ld28LmP/n8SSm6JVZKT8IG55SortkYbwhqUoOJl0guOUSKEldGPwofagtb43FgoURDEpEsBnmWvL3Sr5hHMbzT89UL/ArXwowelFV2cvwOGtMNIklVqR0MU3hXRvxVqf09DHSxQ+Af7Kxdni+t3e9VqHzhDg3dhUkiJa/6MI5vHfAu1npOBMT3b7spMVcYD2fvmAl7rqee6K/i5iguCaXw3iGFNBFbLxb/8RJH4AqBqVmbYZC/quH4vxZsjjyg2r6FYWw0mtHNhGrrZERGdCEnptnuAQigN9xBD"
postgres:
  namespace: news
  version: "13.3"
  image: "postgres:13.3"
  resources:
    requests:
      cpu: 25m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 400Mi
  encryptedEnvs:
    POSTGRES_USER: "AgBzUD2ncC5iabEuOTIQ3yw4tpflKlf/Sb81b4x4ZVx7ohy6je4EMdbc9x5f9Rrwwapbj+qYjz330Q08iRmkOPw2FOHaBwLqSeIlo7dRFHjozUzNCxP9/ldVXk/Ytz6j38eLLAkD9vaI8/cWSMSXn+jQJpc6bBcK959sZA/c3g9DlPgQeUMo6xQnNfLFiE+00b1NNesAWRh+D94SuS+fBTFsWIA2qCAYr9gEXDSgk22AdOpFHWiIuwCOH/x3OmTRm6FVVeVi4jrIWMAEuv77qeEwVUrjnLIYZjmyJWODdgs8wKA4GZ81u1vQ3xtZmZI520G4IpiRWfxFn889C94LX1NNrDGNPKjtvy3F5Tt+sN0w8TwvQsyMHsME0hf8Tm+wpabZk1THk9zppOO1QNR4qf0HgIL+HSZd8jvSMdcKiAdUcDE40OzGODc0cojxSFtYQq6B2RodMARtrOB5f0NLkyrVUIhS+vnx0rsIU5FJ8O0ZNuGPFi8+w9hZzfAvGNkZqO/7doHWnOMGeQ+082wEtyR1xsIwq6RA/6+/wkdQVpZCC0dDWx7Pa47xZ3ebW9p5uKfclhIm2jANFsSR8ULllR/vDzpno3qKV7/qtBIwm/lYToPPXljGhNZRzIbTNH3XhcxQsQ9c7VgdFDrW13AxUSD7+xwup87J2q+V/rOU2VG5N2nDL1ZgvJPQi08RnoEno030Wu7bfW7eOA=="
    POSTGRES_PASSWORD: "AgCOChWccDOsYBL+N3+fDMBC0jRr0E5gRX9JR6KbJQRMfPKunnV6iSxFQj4blfTyxpizSS7F5+U+SrVY50yHE3BoiXRE7JmV0nA16jbXbC6/TyPDUylY+YuCTHnHSHbtDusjoLJny/aX0knVhPaupF3QpnJdsaQUFaMauksTOemn4o/L0TO3iGgzVreuig8yjcYAegqn6skYu7RgzR6ha1w17o5Wai+jTpqoY4CItZsPYbGjpQBneHgox7TDLG2A62kiSvGMh5oSwA/bdLr3UbyLTdyJEnPly9/z36UuZ8cQUshImxBV7N58UVMUax8r5VlnNFVLGK1kJ1uXtnqLc5qEYMd//Pltx26i1J3InbMPutNN0VNxuYCMfsnLSdP1HkFupKYFt/TddHlXYIM30CO02GaHOfrg3QvTduIhrcSi3wcIBHYUY9TzZUtWf3l47BE3enkZlj1ZLHJ5XXaeY7AMw1rqVI/zmBp+0Ayw29UFYfpehg4ThBeJsh/EtmgZjGP4YpJaTCryUtp0xoFVnfvkAbqWWzi9w006kbFvqS15J1UizIrIswdrAdTuek7uqKJ1axmABdaqLE7l7TLpKwVCu+jxJ/doI6tCJgtF2uHzZSqzSYtly7d9hzmQ1GzB9Dx+IaeJYX1qeoQqX9mz9JlM38p25veHeLqOUgUXLvya9OUQ4mwbahC+Y+eNmsJnVeaxsKgMoYFngq6MW6LTNlthY8DOBu7O1nhq9QNjRkbe0s07QnMCCBm4"
  pvcSpec:
    storageClassName: "civo-volume"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
