apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: postgres
    app.kubernetes.io/version: "13.3"
  name: postgres
  namespace: news
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCOChWccDOsYBL+N3+fDMBC0jRr0E5gRX9JR6KbJQRMfPKunnV6iSxFQj4blfTyxpizSS7F5+U+SrVY50yHE3BoiXRE7JmV0nA16jbXbC6/TyPDUylY+YuCTHnHSHbtDusjoLJny/aX0knVhPaupF3QpnJdsaQUFaMauksTOemn4o/L0TO3iGgzVreuig8yjcYAegqn6skYu7RgzR6ha1w17o5Wai+jTpqoY4CItZsPYbGjpQBneHgox7TDLG2A62kiSvGMh5oSwA/bdLr3UbyLTdyJEnPly9/z36UuZ8cQUshImxBV7N58UVMUax8r5VlnNFVLGK1kJ1uXtnqLc5qEYMd//Pltx26i1J3InbMPutNN0VNxuYCMfsnLSdP1HkFupKYFt/TddHlXYIM30CO02GaHOfrg3QvTduIhrcSi3wcIBHYUY9TzZUtWf3l47BE3enkZlj1ZLHJ5XXaeY7AMw1rqVI/zmBp+0Ayw29UFYfpehg4ThBeJsh/EtmgZjGP4YpJaTCryUtp0xoFVnfvkAbqWWzi9w006kbFvqS15J1UizIrIswdrAdTuek7uqKJ1axmABdaqLE7l7TLpKwVCu+jxJ/doI6tCJgtF2uHzZSqzSYtly7d9hzmQ1GzB9Dx+IaeJYX1qeoQqX9mz9JlM38p25veHeLqOUgUXLvya9OUQ4mwbahC+Y+eNmsJnVeaxsKgMoYFngq6MW6LTNlthY8DOBu7O1nhq9QNjRkbe0s07QnMCCBm4
    POSTGRES_USER: AgBzUD2ncC5iabEuOTIQ3yw4tpflKlf/Sb81b4x4ZVx7ohy6je4EMdbc9x5f9Rrwwapbj+qYjz330Q08iRmkOPw2FOHaBwLqSeIlo7dRFHjozUzNCxP9/ldVXk/Ytz6j38eLLAkD9vaI8/cWSMSXn+jQJpc6bBcK959sZA/c3g9DlPgQeUMo6xQnNfLFiE+00b1NNesAWRh+D94SuS+fBTFsWIA2qCAYr9gEXDSgk22AdOpFHWiIuwCOH/x3OmTRm6FVVeVi4jrIWMAEuv77qeEwVUrjnLIYZjmyJWODdgs8wKA4GZ81u1vQ3xtZmZI520G4IpiRWfxFn889C94LX1NNrDGNPKjtvy3F5Tt+sN0w8TwvQsyMHsME0hf8Tm+wpabZk1THk9zppOO1QNR4qf0HgIL+HSZd8jvSMdcKiAdUcDE40OzGODc0cojxSFtYQq6B2RodMARtrOB5f0NLkyrVUIhS+vnx0rsIU5FJ8O0ZNuGPFi8+w9hZzfAvGNkZqO/7doHWnOMGeQ+082wEtyR1xsIwq6RA/6+/wkdQVpZCC0dDWx7Pa47xZ3ebW9p5uKfclhIm2jANFsSR8ULllR/vDzpno3qKV7/qtBIwm/lYToPPXljGhNZRzIbTNH3XhcxQsQ9c7VgdFDrW13AxUSD7+xwup87J2q+V/rOU2VG5N2nDL1ZgvJPQi08RnoEno030Wu7bfW7eOA==
  template:
    data:
      POSTGRES_DB: miniflux
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: postgres
        app.kubernetes.io/version: "13.3"
      name: postgres
      namespace: news
