apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: postgres
    app.kubernetes.io/version: "13.3"
  name: postgres
  namespace: news
spec:
  ports:
  - name: tcp
    port: 5432
    targetPort: tcp
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: postgres
