apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: miniflux
    app.kubernetes.io/part-of: miniflux
    app.kubernetes.io/version: 2.0.33
  name: miniflux
  namespace: news
