apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: flux
  namespace: flux-system
spec:
  groups:
  - name: GitOpsToolkit
    rules:
    - alert: ReconciliationFailure
      expr: max(gotk_reconcile_condition{status="False",type="Ready"}) by (namespace, name, kind) + on(namespace, name, kind) (max(gotk_reconcile_condition{status="Deleted"}) by (namespace, name, kind)) * 2 == 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Flux objects reconciliation failure"
        description: '{{ $labels.kind }} {{ $labels.namespace }}/{{ $labels.name }} reconciliation has been failing for more than ten minutes.'
